### DISCUSSION TITLE
Why run the installation for PR?

### DISCUSSION THREAD

**Discussion by NobodyXu** [GitoxideLabs/gitoxide#1553] [General]
https://github.com/Byron/gitoxide/blob/da08b8bc912c4a89cedb73ef0d0ce627e6e84799/.github/workflows/ci.yml#L156

It simply compiles the one on crates.io which is immutable and not related to the current change in PR/commit.

And it takes 5m to compile and it cannot be cached, because cargo-install uses a temporary target dir by default.

I think it shall be removed, or changed to run only on release, or at least explicitly sets `./target` as target dir so that it can be cached.

**Comment by Byron** [comment]
It can probably be changed to run when a new release-tag is pushed, as this would mean that the version it tries to install is changed.
And after all, this is truly what it should test.
And it's true, the caching stage should also be removed. A PR for that would be very welcome.

```yaml
on:
  push:
    # Enable when testing release infrastructure on a branch.
    # branches:
     #  - fix-releases
    tags:
      - 'v*'
  workflow_dispatch:

```

The above is probably what should trigger it - it's copied from `release.yml`.
